13   S   "^A" BEGINNING OF LINE   - LINE      
15 N S   "^B" CURSOR LEFT                     
8  N S   "^C" EXIT SCREEN EDITOR  - EXIT        
16 N S   "^D" DEL UNDER CURSOR    - DEL->       
13 N     "^E" END OF LINE         - EOL        
6  N S   "^F" CURSOR RIGHT                    
66 N S   "^G" RETURN TO TOP LEVEL - STOP       
72 N S   "^H" BACKWARDS DELETE    - <-DEL      
16 A SA  "^K" ERASE TO EOL        - ALT+DEL->  
79 N S   "^N" DOWN LINE                       
14 N S   "^P" UP LINE                         
12   SA  "^R" TOP OF EDIT BUFFER  - ALT+DOC         
12 A     "^U" UP A PAGE           - ALT+PAGE   
12 N     "^V" DOWN A PAGE         - PAGE       
12   S   "^X" END OF EDIT BUFFER  - DOC
11 N S   "^Y" RECALL LAST LINE    - COPY
3  N S   "^Y" RECALL LAST LINE    - PASTE
