Flip screen display
Find Pattern
Set Breakpoint
Intelligent move
Continue
Disassemble from PC
Set Memory pointer
Find next pattern
Follow relative offset
Fill memory
Load register from MP
Read file
Write file
Show registers
Disassemble a block
Disassemble next page
Reset breakpoint
Restore after rel. off
Restore after address
Disassemble from MP
Follow address at MP
Single step
Repeat Loop
Continue interpreting
Skip over instruction
1. Return to CP/M
2. Alter screen codes
3. Save MON80 as
4. Save MON80 as another file
5. Alter command codes
6. Load Installation from .M80 file
7. Save Installation to .M80 file
^@
^A
^B
^C
^D
^E
^F
^G
^H
^I
^J
^K
^L
[ENTER]
^N
^O
^P
^Q
^R
^S
^T
^U
^V
^W
^X
^Y
^Z
^[
^\
^]
^^
^_
 
!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
0
1
2
3
4
5
6
7
8
9
:
;
<
=
>
?
@
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
[
\
]
^
_
`
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
{
|
}
~
[DEL]
































































































[COPY]
^[TAB]














ð
ñ
ò
ó
[SH]ð
[SH]ñ
[SH]ò
[SH]ó
^ð
^ñ
^ò
^ó
[ESC]

















































SH]ó
^ð
^ñ
^ò
^ó
[ESC]

















