Cursor Up
Cursor Down
Page Up
Page Down
Cursor Right
Cursor Left
Tab
Delete
Escape
1. Return to CP/M
2. Alter screen codes
3. Save ProMON as
4. Save ProMON as another file
5. Alter command codes
6. Load Installation from .P80 file
7. Save Installation to .P80 file
^@
^A
^B
^C
^D
^E
^F
^G
^H
^I
^J
^K
^L
[ENTER]
^N
^O
^P
^Q
^R
^S
^T
^U
^V
^W
^X
^Y
^Z
^[
^\
^]
^^
^_
 
!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
0
1
2
3
4
5
6
7
8
9
:
;
<
=
>
?
@
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
[
\
]
^
_
`
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
{
|
}
~
[DEL]
































































































[COPY]
^[TAB]














p
q
r
s
[SH]p
[SH]q
[SH]r
[SH]s
^p
^q
^r
^s
[ESC]

















































SH]s
^p
^q
^r
^s
[ESC]









