* commment header1
* comment header2
		STOR 1 TO BLAN:XYZ
			DO WHILE X<50
USE DBF1 INDEX DBF1X

STOR B:XYZ+1 TO X
* commment1
* commnet2
ENDDO
		* %SKIP 3
IF Y<3
APPE BLAN
DO SUB1.TRY
ELSE
DO B:SUB2
DO B:SUB2.CMD
IF Z=3
STOR 6 TO Z
ENDIF
ENDIF
IF X>10
  IF X>10
   IF X>10
     IF X>10
       IF X>10
                                                               ? 'AAAAAAAAAAAAAAAAAAAAAAA' + 'BBBBB'
								? 'AAAAAAAAAAAAAAAAAAAAA' + 'BBBBBB'
? 'KAFALFJALDKFJALFDJFLDJFLJLDJFLSDFJGHSFHAKDJFAFSDFAS'
 ? 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  ENDIF
ENDIF
ENDIF
ENDIF
ENDIF
