;do not include the .BAS extension in param source filename
; drive B: is CB80 compiler disk
; drive C: is sources & compiled files (.REL) disk
; drive A: is where the .COM file & symbol file (.SYM produced by linker) is placed
B:
ERA A:$1.COM
CB80 C:$1[B]
LK80 A:$1=C:$1
GENGRAF A:$1
ERA C:$1.REL
ERA A:$1.SYM
A:
; in order to run, the compiled .COM file needs on same unit
; GSX.SYS, ASSIGN.SYS and DDXTEK.PRL (or any other GSX driver)
$1

