Compilation notes for xrefc(q)
TIC file - 27k.  MAC file 82k.

If recompiling .PCD, use parm=64 to ASSMPCD for single segment
(over-riding source segmentation commands)

This version (2.6) requires PASCLIB 2.6.1 or up at link time,
and the .PCD versions require interpreters linked to that library.

(because of use of read(string) -- PascalP 3.1.8 up compiles)

Comparitive performance on 475 line C source file, listing to console:

    XREFC.COM      90 sec.
    XREFC.PCD     210 sec.         (2.5 Mhz. Kaypro 4-83)
DV