pip a:=b:lnk.com
pip a:=b:crtx.o
lnk -u_main -eb__memory -tb0x100 -htr -o a80.com crtx.o b:asmlib.80 b:libc.80
lnk -eb__memory -tb0x100 -htr -o lby.com crtx.o b:lib.o b:libc.80
lnk -eb__memory -tb0x100 -htr -o lrd.com crtx.o b:lord.o b:libc.80
lnk -eb__memory -tb0x100 -htr -o hex.com crtx.o b:hex.o b:libc.80
lnk -eb__memory -tb0x100 -htr -o rel.com crtx.o b:rel.o b:libc.80
pip a:=b:libc.80
