CC1:
fopen::
PUSH B
LXI H,0
DAD SP
XCHG;;
LXI H,0
CALL CCPINT##
CC3:
LXI H,0
CALL CCINCI##
XCHG;;
LXI H,10
CALL CCLT##
MOV A,H
ORA L
JZ CC4
POP H
PUSH H
PUSH H
CALL Umode
POP B
MOV A,H
ORA L
JNZ CC5
LXI H,6
CALL CCDSGI##
PUSH H
LXI H,6
CALL CCDSGI##
PUSH H
LXI H,4
CALL CCDSGI##
PUSH H
CALL Uopen
POP B
POP B
POP B
XCHG;;
LXI H,-2
CALL CCNE##
MOV A,H
ORA L
JZ CC6
POP H
PUSH H
POP B
RET
CC6:
JMP CC4
CC5:
JMP CC3
CC4:
LXI H,0
POP B
RET
EXT Uopen
EXT Umode
END
