\wg11
>a1:"    TERM
>a1:\dc0
>b1:" choice
>b1:\wc0
>c1:"   ANNUAL
>c1:\wc11
>d1:\wc0
>e1:\wc0
>f1:"  PRINCIPAL
>f1:\dc2
>g1:"  MONTHLY
>h1:"INITIAL YR:
>h1:\wc13
>i1:\wc13
>a2:" IN MONTHS
>b2:"function
>c2:" PERCENTAGE
>f2:"    AMOUNT
>g2:"  PAYMENT
>h2:"      YEAR?
>a3:" (if known)
>b3:" for term:
>c3:"    RATE
>d3:"  choice
>f3:" (if known)
>g3:"(if known)
>h3:"INITIAL MO:
>i3:"   (c) 1983
>a4:"  TERM ?
>b4:=gtr(0,lsr(a4+1,1-a4)
>c4:"  RATE ?
>d4:" functions
>f4:" AMOUNT ?
>g4:" PAYMENT ?
>h4:"     MONTH?
>i4:"    Ronald
>a5:"-----------
>b5:"-----------
>c5:"-----------
>d5:" for princ:
>e5:"-----------
>f5:"-----------
>g5:"-----------
>h5:"-------------
>i5:"     Knill
>a6:"  COMPUTED
>b6:=c4/1200+1e-8
>c6:"   MONTHLY
>d6:=100*gtr(0,lsr(f4+.01,.01-f4
>e6:=g9/b6
>f6:"  COMPUTED
>g6:" COMPUTED
>h6:"BEGIN MONTHLY
>a7:"    TERM
>b7:=exp(gtr(a9*ln(1+b6),1e-8)
>c7:" PERCENTAGE
>d7:" for pymnt:
>e7:" =pymnt/int
>f7:"  PRINCIPAL
>g7:"  MONTHLY
>h7:" AMORTIZATION
>a8:" IN  MONTHS
>b8:=ln(1+b6
>c8:"    RATE
>d8:=100*gtr(0,lsr(g4+.01,.01-g4
>e8:"-----------
>f8:"    AMOUNT
>g8:"  PAYMENT
>h8:"  IN YEAR.MO?
>a9:=a4+int(b4/b8*ln((g4+1e-8)/(abs(g4-b6*f4)+1e-8))+.999
>c9:=c4/12
>e9:=lsr(13-h4,12)
>f9:=f4+.01*d6*int(100*g4*(b7-1)/(b6*b7
>g9:=g4+.01*d8*int(100*b6*b7*f4/(b7-1)+.999
>h9:=h2+.01*h4
>a10:"-----------
>b10:"-----------
>c10:"-----------
>d10:"-----------
>e10:"-----------
>f10:"-----------
>g10:"-----------
>h10:"-------------
>i10:"-------------
>a11:"***********
>c11:"***********
>f11:"***********
>g11:"***********
>h11:"*************
>i11:"*************
