; script to build DEFF from STDLIB.C and DEFF2.C
; rewitten by Roberto Sancho Dec 2023
; deff3 is not compiled here because should be manually compiled and
; patched with machine code
xsub
cc1 stdlib.c
cc2 stdlib
cc1 deff2.c
cc2 deff2
era deff.crl
clib
m deff
o 0 deff
o 1 stdlib
o 2 deff2
o 3 deff3
f
t 1 0 *
t 2 0 *
t 3 0 *
l 0
c 0
q
era deff.brl
era deff2.crl
era stdlib.crl
