;
;	GSX-80 driver for CPM Player emulator
;	Copyright (C) 2024 by Roberto Sancho
;
	CSEG

;	Entry for the ddcpmply driver
;
CPMPLY:	DB	0EDh, 0FCh	; z80 trap instruction for GSX 
	RET

   	DB	'---------------------------------------------------',13,10
	DB	'CPM Player GSX Driver                   Version 1.0',13,10
	DB	'Copyright (c) 2024 by Roberto Sancho               ',13,10
	DB	'---------------------------------------------------',13,10

	END
