;do not include the .PAS extension in param source filename
;compile to 8080 asm into .COM file
INTERPC pascalp ($1.pas, con, $1.tic)
assmap ($1.tic, $1.asm) 
era $1.tic
slrmac $1.@@z/fr
era $1.slr
ren $1.slr=$1.rel
era $1.mac
slrnk /a:100,cpmlink,$1,pasclib/s,$1/n,/e
era EXTRNLS
era $1.asm
era $1.slr
$1
                                                                                                    