:This submit file will accept as an argument the name of the file
:to compile, assemble, link and run. For this file to work correctly,
:PASCAL.COM, PAS2, ASMBL.COM, LINK.COM, MAIN.SRC and LIB.REL must be
:on drive A. The file to compile must be on the drive specified by the
:second argument to this routine:
: e.g.  submit compile myprog c
:will compile myprog.pas on drive c
Pascal $1.$2$2$2
asmbl main,$1.$2$2/rel
link /n:$2:$1 $2:$1 /g
