; build all
link -eb__memory -ed__edata -tb0x100 -htro as80.com crts.80 as.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro pp.com crts.80 p0.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro p1.com crts.80 p1.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro p280.com crts.80 p2.o libc.80
;link -eb__memory -ed__edata -tb0x100 -htro link.com crts.80 link.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro anat.com crts.80 anat.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro cpm.com crts.80 cpm.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro dis80.com crts.80 dis80.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro hex.com crts.80 hex.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro lib.com crts.80 lib.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro lord.com crts.80 lord.o libc.80
link -eb__memory -ed__edata -tb0x100 -htro rel.com crts.80 rel.o libc.80
