
; Build Floating Point version

era xycpmfp.com
era xycpmfp.asm
era xycpmfp.prn
era xycpmfp.hex
era xycpmfp.sym
pip xy.1=vercpmfp,aux1,cpm,driver,eval,finout,fmath,fpbcd,fnsops,inout,parsing
pip xy.2=sdisk,stacks,states1,states2,states3,strings,tables
pip xy.3=tokenize,xmath,ram,initial
pip xycpmfp.asm=xy.1,xy.2,xy.3
era xy.*
mac xycpmfp
load xycpmfp

; Build BDC version

era xycpmbcd.com
era xycpmbcd.asm
era xycpmbcd.prn
era xycpmbcd.hex
era xycpmbcd.sym
pip xy.1=vercpmbc,aux1,cpm,driver,eval,finout,fmath,fpbcd,fnsops,inout,parsing
pip xy.2=sdisk,stacks,states1,states2,states3,strings,tables
pip xy.3=tokenize,xmath,ram,initial
pip xycpmbcd.asm=xy.1,xy.2,xy.3
era xy.*
mac xycpmbcd
load xycpmbcd
