%nolist
rem		The following list of external function
rem	declarations is included for your convenience.

	def alteos external
		integer alteos
	fend

	def amm(p1) external
		integer amm
		string p1
	fend

	def amo(p1) external
		integer amo
		string p1
	fend

	def aom(p1) external
		integer aom
		string p1
	fend

	def aoo(p1) external
		integer aoo
		string p1
	fend

	def aui(p1) external
		integer aui
		string p1
	fend

	def ccu(p1) external
		integer ccu
		string p1
	fend

	def cra(p1) external
		integer cra
		string p1
	fend

	def crs(p1) external
		integer crs
		string p1
	fend

	def dbcls external
		integer dbcls
	fend

	def dbclsa(p1) external
		integer dbclsa
		string p1
	fend

	def dbenv(p1) external
		integer dbenv
		string p1
	fend

	def dbopn(p1) external
		integer dbopn
		string p1
	fend

	def dbopna(p1) external
		integer dbopna
		string p1
	fend

	def dbsave external
		integer dbsave
	fend

	def dbstat(p1) external
		integer dbstat
		string p1
	fend

	def define(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11) external
		integer define,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11
		string p1
	fend

	def drc external
		integer drc
	fend

	def drm(p1) external
		integer drm
		string p1
	fend

	def dro(p1) external
		integer dro
		string p1
	fend

	def extend(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11) external
		integer extend,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11
		string p1
	fend

	def fdrk(p1) external
		integer fdrk
		string p1
	fend

	def ffm(p1) external
		integer ffm
		string p1
	fend

	def ffo(p1) external
		integer ffo
		string p1
	fend

	def ffs(p1) external
		integer ffs
		string p1
	fend

	def flm(p1) external
		integer flm
		string p1
	fend

	def flo(p1) external
		integer flo
		string p1
	fend

	def fmi(p1) external
		integer fmi
		string p1
	fend

	def fmsk(p1) external
		integer fmsk
		string p1
	fend

	def fnm(p1) external
		integer fnm
		string p1
	fend

	def fnmi(p1) external
		integer fnmi
		string p1
	fend

	def fnmsk(p1) external
		integer fnmsk
		string p1
	fend

	def fno(p1) external
		integer fno
		string p1
	fend

	def fnoi(p1) external
		integer fnoi
		string p1
	fend

	def fnosk(p1) external
		integer fnosk
		string p1
	fend

	def fns(p1) external
		integer fns
		string p1
	fend

	def foi(p1) external
		integer foi
		string p1
	fend

	def fosk(p1) external
		integer fosk
		string p1
	fend

	def fpm(p1) external
		integer fpm
		string p1
	fend

	def fpo(p1) external
		integer fpo
		string p1
	fend

	def frk(p1) external
		integer frk
		string p1
	fend

	def getc(p1) external
		integer getc
		string p1
	fend

	def getm(p1) external
		integer getm
		string p1
	fend

	def geto(p1) external
		integer geto
		string p1
	fend

	def gfc(p1) external
		integer gfc
		string p1
	fend

	def gfm(p1) external
		integer gfm
		string p1
	fend

	def gfo(p1) external
		integer gfo
		string p1
	fend

	def gmc(p1) external
		integer gmc
		string p1
	fend

	def goc(p1) external
		integer goc
		string p1
	fend

	def gtc(p1) external
		integer gtc
		string p1
	fend

	def gtm(p1) external
		integer gtm
		string p1
	fend

	def gto(p1) external
		integer gto
		string p1
	fend

	def ims(p1) external
		integer ims
		string p1
	fend

	def ios(p1) external
		integer ios
		string p1
	fend

	def lgcplx external
		integer lgcplx
	fend

	def lgendx external
		integer lgendx
	fend

	def lgfile(p1) external
		integer lgfile
		string p1
	fend

	def lgflsh external
		integer lgflsh
	fend

	def lgmsg(p1) external
		integer lgmsg
		string p1
	fend

	def nci external
		integer nci
	fend

	def pfc(p1) external
		integer pfc
		string p1
	fend

	def pfm(p1) external
		integer pfm
		string p1
	fend

	def pfo(p1) external
		integer pfo
		string p1
	fend

	def pifd(p1) external
		integer pifd
		string p1
	fend

	def putc(p1) external
		integer putc
		string p1
	fend

	def putm(p1) external
		integer putm
		string p1
	fend

	def puto(p1) external
		integer puto
		string p1
	fend

	def rms(p1) external
		integer rms
		string p1
	fend

	def ros(p1) external
		integer ros
		string p1
	fend

	def rsm(p1) external
		integer rsm
		string p1
	fend

	def rso(p1) external
		integer rso
		string p1
	fend

	def scm(p1) external
		integer scm
		string p1
	fend

	def scn external
		integer scn
	fend

	def sco(p1) external
		integer sco
		string p1
	fend

	def scu(p1) external
		integer scu
		string p1
	fend

	def setpbf(p1,p2) external
		integer setpbf,p1,p2
	fend

	def smc(p1) external
		integer smc
		string p1
	fend

	def sme(p1) external
		integer sme
		string p1
	fend

	def smm(p1) external
		integer smm
		string p1
	fend

	def smn(p1) external
		integer smn
		string p1
	fend

	def smo(p1) external
		integer smo
		string p1
	fend

	def smu(p1) external
		integer smu
		string p1
	fend

	def soc(p1) external
		integer soc
		string p1
	fend

	def soe(p1) external
		integer soe
		string p1
	fend

	def som(p1) external
		integer som
		string p1
	fend

	def son(p1) external
		integer son
		string p1
	fend

	def soo(p1) external
		integer soo
		string p1
	fend

	def sou(p1) external
		integer sou
		string p1
	fend

	def suc(p1) external
		integer suc
		string p1
	fend

	def sum(p1) external
		integer sum
		string p1
	fend

	def sun(p1) external
		integer sun
		string p1
	fend

	def suo(p1) external
		integer suo
		string p1
	fend

	def suu(p1) external
		integer suu
		string p1
	fend

	def tct(p1) external
		integer tct
		string p1
	fend

	def tmt(p1) external
		integer tmt
		string p1
	fend

	def tot(p1) external
		integer tot
		string p1
	fend

	def trabt external
		integer trabt
	fend

	def trbgn external
		integer trbgn
	fend

	def trcom external
		integer trcom
	fend

	def undef external
		integer undef
	fend

	def xmm(p1) external
		integer xmm
		string p1
	fend

	def xmo(p1) external
		integer xmo
		string p1
	fend

	def xom(p1) external
		integer xom
		string p1
	fend

	def xoo(p1) external
		integer xoo
		string p1
	fend

%list
