;
; SUBMIT job to build the library GLIB.REL
; Must be submitted from A:
;

xsub
;
E:
; compile modules
m80 =gcons
f80 =ginit
f80 =gclose
f80 =gclear
f80 =grect
f80 =garc
f80 =gwind
f80 =gview
f80 =gaxis
f80 =gaxlab
f80 =gspen
f80 =gsmark
f80 =gmark
f80 =grast
f80 =gnum
f80 =gtext
f80 =gchsiz
f80 =gchar
f80 =gmovec
f80 =gdrawc
f80 =gclip
f80 =gmove
f80 =gdraw
f80 =gimove
f80 =gidraw
f80 =gtrafo
f80 =ghatch
f80 =gpoly
; build library
lib80
glib=ginit,gclose,gclear,gcons,grect,garc,gwind,gview,gaxis,gaxlab
grast,gnum,gtext,gchar,gmove,gdraw,gmovec,gdrawc,gclip,gimove,gidraw
gchsiz,gspen,gsmark,gmark,gpoly,gtrafo,ghatch
/E
; build demo programs
f80 =gdemo1
l80 gdemo1/N,gdemo1,glib/S,gsxlib/S,forlib/S,/E
gengraf gdemo1
;
f80 =gdemo2
l80 gdemo2/N,gdemo2,glib/S,gsxlib/S,forlib/S,/E
gengraf gdemo2
;
f80 =gdemo3
l80 gdemo3/N,gdemo3,glib/S,gsxlib/S,forlib/S,/E
gengraf gdemo3
; Done.
