; compile for GLIB
; no .FOR extension on parameter
B:
f80 =C:$1
pip b:=c:$1.rel
era c:$1.rel
l80 $1/N,$1,glib/S,gsxlib/S,forlib/S,/E
gengraf $1
era $1.rel
pip a:=$1.com
era $1.com
A:
; in order to run, the compiled .COM file needs on same unit
; GSX.SYS, ASSIGN.SYS and DDXTEK.PRL (or any other GSX driver)
$1

