      PROGRAM EXAMPLE
C
C    This program demonstrates the use of the READ, WRITE, and 
C    FORMAT statements to do Input and Output to the terminal.
C
C    The Logical Unit Number for the console terminal is 3, so that
C    number is used in the FORMAT statements.
C
C    The values entered by the operator in response to the prompts
C    generated by this program must be in the form specified for
C    I FORMAT input in Section 8 of the FORTRAN manual.
C
      INTEGER J, K, L
C
C    The next lines write a message on the terminal to prompt the
C    operator to enter the value of J.
C
        WRITE (3, 10)
10      FORMAT (1X, 'J = ')
C
C    The next lines read the value typed by the operator and store
C    it in the Integer variable J.
C
        READ (3, 11) J
11      FORMAT (I7)
C
C    The next lines write a message on the terminal to prompt the
C    operator to enter the value of K.
C
        WRITE (3, 12)
12      FORMAT (1X, 'K = ')
C
C    The next line reads the value typed by the operator and stores
C    it in the Integer variable K.  An existing FORMAT statement is 
C    used by the READ statement.
C
        READ (3, 11) K
C
C    The next lines compute the sum of the two variables J and K
C    and write the value of the result on the screen of the terminal.
C
        L = J + K
        WRITE (3, 13) L
13      FORMAT (1X, 'J + K = ', I7, /)
        END
