	      	                     	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	
 
 
 
 
                          Ready to print FILENAME
 
 
            * * * * * * * * * * * * * * * * * * * * * * * * * *
            *                                                 *
            *        Prepare printer for printing, and        *
            *                                                 *
            *           press SPACE BAR when ready            *
            *                                                 *
            * * * * * * * * * * * * * * * * * * * * * * * * * *
 
 
                            Use <CTRL>-Q to quit.
