	      	                     	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	
 
 
 
 
<record>
  Product: {product}  Price: {price>}  Quantity: {qua>}
<end>
  Product: Model 1a   Price:    35.51  Quantity:     56
  Product: Model 1b   Price:    42.79  Quantity:     23
  Product: Model 1c   Price:    67.99  Quantity:     27
  Product: Model 1d   Price:    78.49  Quantity:     12
      {#height>}
<end>
Name:        Smith, Arnold
Street:      123 First Street
City/State:  Berkeley, CA 94704
Work Tel:    456-7890
Home Tel:    876-5432
Weight:      165
Height:      68
Name:        Roberts, Philip
Street:      345 Fourth Street
City/State:  Danville, CA 93101
Work Tel:    345-3210
Home Tel:    234-0989
Weight:      245
Height:      75
Name:  