	                                   	                                                                                                                                                                                                                                                                       
 
 
 
<record>
Name:        {lastname            } {firstname         }
Street:      {street                                   }
City/State:  {city.state                               }
Work Tel:    {worktel                                  }
Home Tel:    {hometel                                  }
<end>
Name:        Adams                  Adam
Street:      567 Eden Garden
City/State:  Paradise, CA 92003
Work Tel:    none
Home Tel:    334-5679
Name:        Baker                  Buster
Street:      5467 Riverside Drive
City/State:  Riverside, CA 98772
Work Tel:    223-6548
Home Tel:    332-5297
Name:        Blues                  Bertha D.
Street:      124 Musical Way
City/State:  Berkeley, CA 94710
Work Tel:    233-9473
Home Tel:    466-2456
Name:        Cassio                 Bruce
Street:      44332 Digital Drive
City/State:  El Cerrito, CA 94665
Work Tel:    342-7643
Home Tel:    293-2593
Name:        Davis                  David
Street:      765 Davidson Place
City/State:  Davis, CA 98776
Work Tel:    359-9724
Home Tel:    285-8374
Name:        Edwards                Edward
Street:      33556 Eddington Street
City/State:  Edwards AFB, CA 97443
Work Tel:    459-3322
Home Tel:    567-2231
Name:        Fauna                  Flora
Street:      1234 17th Street
City/State:  San Francisco, CA 94121
Work Tel:    233-5577
Home Tel:    245-8743
Name:        Gordon                 Flash
Street:      4553 Heavenly Valley Road
City/State:  Stateline, Nevada 87678
Work Tel:    457-3647
Home Tel:    227-2211
Name:        Hun                    Attila
Street:      2344 Caspian Way
City/State:  Berkeley, CA 94567
Work Tel:    233-4533
Home Tel:    none
Name:        Invasion               Norman
Street:      1066 English Lane
City/State:  Berkeley, CA 94709
Work Tel:    344-9275
Home Tel:    245-9346
Name:        Jackson                Jack
Street:      1334 Jones Street
City/State:  Jefferson City, CA 93211
Work Tel:    334-1234
Home Tel:    556-2311
Name:        Roberts                Philip
Street:      345 Fourth Street
City/State:  Danville, CA 93101
Work Tel:    345-3210
Home Tel:    234-0989
Name:        Smith                  Arnold
Street:      123 First Street
City/State:  Berkeley, CA 94704
Work Tel:    456-7890
Home Tel:    876-5432
Name:        Thomas                 Richard
Street:      678 Ninth Street
City/State:  San Francisco, CA 94111
Work Tel:    546-2314
Home Tel:    472-8744
City/State:  Stateline, Nevada 87678
Work Tel:    457-3647
Home Tel:    227-2211
Name:        Hun                    Attila
Street:      2344 Caspian Way
City/State:  Berkeley, CA 94567
Work Tel:    233-4533
Home Tel:    none
Name:        Invasio