	      	                     	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	
<record>
.new
 {!firstname             } {lastname                }
 {street                                   }
 {city.state                               }
<end>
.pagesize 9
..<here>
Street
City/State:  Berkeley, CA 94704
Work Tel:    456-7890
Home Tel:    876-5432
Name:        Thomas                 Richard
Street:      678 Ninth Street
City/State:  San Francisco, CA 94111
Work Tel:    546-2314
Home Tel:    472-8744
City/State:  Stateline, Nevada 87678
Work Tel:    457-3647
Home Tel:    227-2211
Name:        Hun                    Attila
Street:      2344 Caspian Way
City/State:  Berkeley, CA 94567
Work Tel:    233-4533
Home Tel:    none
Name:        Invasio