 
 
 
 
<record>
Customer:  {customer           }
Product:   {product            }
Quantity:  {quantity>}
<end>
Customer:  ACME
Product:   Mirrors
Quantity:          150
Customer:  ACME
Product:   Windows
Quantity:           23
Customer:  General Supply
Product:   Mirrors
Quantity:           45
Customer:  General Supply
Product:   Windows
Quantity:           30
Customer:  ACME
Product:   Doors
Quantity:           12
Customer:  General Supply
Product:   Doors
Quantity:           14
Customer:  Smith Const.
Product:   Mirrors
Quantity:          150
Customer:  Smith Cons.
Product:   Windows
Quantity:           30
Customer:  ACME
Product:   Mirrors
Quantity:          150
Customer:  Smith Cons.
Product:   Doors
Quantity:           30
Customer:  ACME
Product:   Mirrors
Quantity:          150
Customer:  General Supply
Product:   Windows
Quantity:           30
