	      	         	           	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	         	
 
 
 
<record>
Name:        {name                                     }
Street:      {street                                   }
City/State:  {city.state                               }
Work Tel:    {worktel                                  }
Home Tel:    {hometel                                  }
Weight:      {w#eight>}
Height:      {#height>}
<end>
Name:        Smith, Arnold
Street:      123 First Street
City/State:  Berkeley, CA 94704
Work Tel:    456-7890
Home Tel:    876-5432
Weight:      165
Height:      68
Name:        Roberts, Philip
Street:      345 Fourth Street
City/State:  Danville, CA 93101
Work Tel:    345-3210
Home Tel:    234-0989
Weight:      245
Height:      75
Name:        Thomas, Richard
Street:      678 Ninth Street
City/State:  San Francisco, CA 94111
Work Tel:    546-2314
Home Tel:    472-8744
Weight:      143
Height:      70
       	         	         	         	
 
 
 
<record>
Name:        {name                                     }
Street:      {street                                   }
City/State:  {city.state                               }
Work Tel:    {worktel                                  }
Home Tel:    {hometel                                  }
Weight:      {w#eight>}
Height:      {#height>}
<end>
Name:        Smith, Arnold
Street:      123 First Street
City/State:  Berkeley, CA 94704
Work Tel:    456-7890
Home Tel:    876-5432
Weight:      165
Height:      68
Name:        Roberts, Philip
Street:      345 Fourth Street
City/State:  Danville, CA 93101
Work Tel:    345-3210
Home Tel:    234-0989
Weight:      245
Height:      75
Name:  