10 PRINT
20 PRINT "HiSoft C++ Compiler"
30 PRINT
40 PRINT "This side of the disc contains"
45 PRINT " the CP/M compiler HC.COM"
50 PRINT
60 PRINT "To use it, you must first start up CP/M"
65 PRINT "by putting your CP/M system disc into"
70 PRINT "the drive and using the |CPM command."
80 PRINT
90 PRINT "Enjoy yourself."
100 PRINT
110 PRINT "Dave Howorth"
120 PRINT "3 Oct 85"
and using the |CPM command."
80 PRINT
90 PRINT "Enjoy yourself."
100 PRINT
110 PRINT "Dave Howorth"
120 PRINT "3 O