
<today>


<name>
<address>

<salutation(name)>

      Perfect Filer is here!  Yes, one of the most advanced,
versatile, easy-to-use file management systems for
micro-computers today is at last available.  Complete with mail
and list capabilities and integrated with the Perfect Writer word
processor, Perfect Filer offers numerous applications for your
business activities.

      Two pre-structured data bases allow you to begin using
the system immediately.

      Easy menu-guided programs allow the creation of
individualized data bases to meet all of your file management
needs.

      Versatile sort routines, multiple subset definition, easy
list format procedures make file management an undreamed of
convenience!

      We are sure that you will find Perfect Filer an
indispensable administrative and management tool for
<address.organization>.

      For further information, please call or write us at:

                         Perfect Software, Inc.
                         1400 Shattuck Avenue
                         Berkeley, CA  94709

                         (415)  644-3644


                                        Sincerely,


                                        Perfect Software, Inc.

and list capabiliti