/****************************************/
/*					*/
/*	Q/C Standard I/O Definitions	*/
/*					*/
/****************************************/

/* #include "qstdio.h" */

/* General purpose constansts */

#define ERROR	-1
#define EOF	-1
#define NULL	0
#define TRUE	1
#define FALSE	0

/* standard I/O device names for redirection */

extern	stdin,
	stdout,
	stderr,
	stdlst;
