ARK04P is an ARK/ARC archive file maker for CP/M.  It requires a Z80
CPU and about 48K of TPA to run.  ARK04 fixes several bugs in ARK035.
The problem with certain files being unARKable has been fixed, as
have problems with systems like the Osborne Executive that use the IX
and IY registers.  This ver. adds file time stamping for CP/M Plus.
File timestamp defaults to current time if timestamps not enabled for
the particular drive.  Dated December 04, 1988.
