; compile a source program to disk
XSUB
ERA $1.BZS
ERA $1.COM
BZ $1.BAS
;expect "Spaceleft"
;wait 100
LIST
;expect "END"
;wait 100
TITLE $1
;expect "Title"
;wait 100
SAVE $1
;expect "format"
;wait 100
COMPILE $1
;expect "BASIC/Z"
;wait 100
BIND
;expect "library"
;wait 100
RZ
;expect "compiled program"
;wait 100
HELLO
;expect "destination file"
;wait 100
HELLO
;expect "BASIC/Z"
;wait 100
DOS
$1
