
Directory For Drive B:  User  0

    Name     Bytes   Recs   Attributes      Name     Bytes   Recs   Attributes 
------------ ------ ------ ------------ ------------ ------ ------ ------------
-CONTENT COB     0k      0 Dir RW       CC       COM     7k     50 Dir RW      
CONFIG   CBL     9k     72 Dir RW       CONVHEX  COM     2k     16 Dir RW      
ERRORS   COM     1k      6 Dir RW       READ     ME      2k     10 Dir RW      
RENUMBER CBL     5k     39 Dir RW       RUN      COM    12k     94 Dir RW      
W4       COM    30k    236 Dir RW       W5       CBL     8k     61 Dir RW      

Total Bytes     =     76k  Total Records =     584  Files Found =   10
Total 1k Blocks =     76   Used/Max Dir Entries For Drive B:   11/  64

         ++++++++++ September 1st 1985 New Star Software ++++++++++++this is achieved simply by returning control to MASTERFILE proper, via
GOTO 70, and then invoking the file save function.


