.error
.item 0 welcome
Welcome to CLIP version 2.2	  	       (C) 1982, 1983  ARTISOFT, Inc.
.item 1 nocmnd
Command does not exist - |
.item 2 badswi
OÎ oò OFÆ argumenô noô present
.item 7 fnotf
File does not exist - |
.item 9 fexists
File already exists - |
.item 10 psunf
Internal macro does not exit - |
.item 11 SWPERR
Error while swapping:  check CLIPSWAP.OVL on disk A:
.item 12 IFCOND
Allowable conditions for IF command are <, <=, =, =>, >, and <>
.item 13 NOIF
An IF command needs to preceed this command
.item 14 CALCERR
Valid CALC functions are +, -, *, /, &, !, X, and '
.item 15 NOCHAIN
Attempting to CHAIN to a nonexistent file
.item 16 OPFNF
File not found in OPEN command
.item 17 OPFNC
File number is in use: A CLOSE needs to preceed this OPEN
.item 18 OPMHS
OPEN command must have I or O switch
.item 19 OPNDS
No directory space for OPEN
.item 20 CLONR
Disk space exhausted: DELete unwanted files and reissue the command
.item 21 ERFNO 
A file must be OPENed before any I/O can occur
.item 22 ERNIF
This file is not OPEN for input
.item 23 ERNOF
This file is not OPEN for output
.item 24 ERNOR
Disk space has been exhausted by PUT
.item 25 ERROF
Output redirection has failed: No directory space
.item 26 ERRIF
Input redirection has failed: File does not exist
.item 29 RETCTRL
                            [Exiting to CP/M]
                                Good bye!

.item 30 ILLSIZ
Bad switch values have been specified for SUBSTR
.item 32 NOARGS
This command requires argument(s)
.item 33 REXIST
RENaming to an exiting file is not allowed:
DELete the destination file if you wish to rename to it
.item 34 NODIRS
Directory space has been exausted
.item 35 NATL
This command is only valid from within a command (macro) file
.item 36 tml	
Macro nested too many levels
.item 37 uedcerr	
Unknown command, please correct it:
.item 38 uednfnd	
String not found
.item 39 cpydf	
Can't COPY: Disk is full
.item 40 cpyfnfs 
Source file does not exist
.item 42 dwdf	
Are you sure you want to DELETE ALL you files (Y or N)? |
.item 43 fndel	
--Delete canceled
.item 45 delmhvr	
Improper range for DEL command, please correct it:
.item 46 nohlpf
The help message file cannot be located:
Make sure you have copied it properly from the distribution disk
.item 47 nohlpt
No help or information is available for that topic
.item 48 memover
Your file is too big to fit in memory:
Reissue the command with the /M switch if you still want to edit the file
.item 49 ttbo
Memory full:  Can't insert any more characters in text buffer
.item 50 errfse
There is no more room on the disk to write out your file
.item 51 wildno
The wildcard characters ? and * are not allowed in this command
.item 52 ltl
This line is too long to be processed by CLIP
.end
